package com.crm.settings.mapper;

import com.crm.settings.entity.DictionaryType;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DictionaryTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Mar 07 15:30:14 CST 2023
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Mar 07 15:30:14 CST 2023
     */
    int insert(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Mar 07 15:30:14 CST 2023
     */
    int insertSelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Mar 07 15:30:14 CST 2023
     */
    DictionaryType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Tue Mar 07 15:30:14 CST 2023
     */
    int updateByPrimaryKeySelective(DictionaryType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *  条件
     *
     * @mbggenerated Tue Mar 07 15:30:14 CST 2023
     */
    int updateByPrimaryKey(DictionaryType record);

    List<DictionaryType> selectDictionTypeList();

    int insertDicType(DictionaryType dictionaryType);

    List<String> selectCodeList();

    int updateByDictionaryType(DictionaryType dictionaryType);

    int deleteDicTypeByCodes(@Param("codes") String[] codes);
}