package com.crm.workbench.mapper;

import com.crm.workbench.entity.Activity;
import com.crm.workbench.entity.ActivityRemark;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface ActivityRemarkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Wed Sep 07 08:52:02 CST 2022
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Wed Sep 07 08:52:02 CST 2022
     */
    int insert(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Wed Sep 07 08:52:02 CST 2022
     */
    int insertSelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Wed Sep 07 08:52:02 CST 2022
     */
    ActivityRemark selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Wed Sep 07 08:52:02 CST 2022
     */
    int updateByPrimaryKeySelective(ActivityRemark record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_activity_remark
     *
     * @mbggenerated Wed Sep 07 08:52:02 CST 2022
     */
    int updateByPrimaryKey(ActivityRemark record);

    /**
     * 根据ActivityId查询该市场活动下所有的备注的明细信息
     *
     * @param activityId
     * @return java.util.List
     */
    List<ActivityRemark> selectActivityRemarkForDetailByActivityId(String activityId);
    /**
     * 插入市场活动备注
     */
    int insertActivityRemark(@Param("activityRemark") ActivityRemark activityRemark);

}