package com.crm.settings.entity;

import lombok.Data;
import org.apache.ibatis.type.Alias;

@Alias("dicValue")
@Data
public class DicValue {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.id
     *
     * @mbggenerated Thu Sep 08 19:24:49 CST 2022
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.value
     *
     * @mbggenerated Thu Sep 08 19:24:49 CST 2022
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.text
     *
     * @mbggenerated Thu Sep 08 19:24:49 CST 2022
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.order_no
     *
     * @mbggenerated Thu Sep 08 19:24:49 CST 2022
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_dic_value.type_code
     *
     * @mbggenerated Thu Sep 08 19:24:49 CST 2022
     */
    private String typeCode;
}